import Footer from '@/components/templates/Footer'
import Header from '@/components/templates/Header'
import locales from '@/i18n/locales'
import { NextIntlClientProvider } from 'next-intl'
import {getMessages} from 'next-intl/server'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

// export const metadata = {
// 	title: 'United to give',
// 	description: 'Generated by create next app',
// }

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export async function generateMetadata({ params: { locale } }) {
  return {
    title: locale.toUpperCase(),
  }
}

export default async function LocaleLayout({ children, params: { locale } }) {
	// const messages = await getMessages()
	// const locale = await params.locale
	if (!locales.includes(locale)) notFound()
		// unstable_setRequestLocale(locale)
	
		const messages = (await import(`@/i18n/messages/${locale}.json`)).default

	return (
		<html lang={locale}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<div className="w-dvw h-dvh">
						<Header locale={locale}/>
						{children}
						<Footer />
					</div>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
