import Footer from '@/components/templates/Footer'
import Header from '@/components/templates/Header'
import { NextIntlClientProvider } from 'next-intl'
import {getMessages} from 'next-intl/server'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'United to give',
  description: 'Generated by create next app',
}

export default async function RootLayout({
																					 children,
																					 params
																				 }) {
  const messages = await getMessages()
  const locale = await params.locale

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <div className="w-dvw h-dvh">
            <Header locale={locale}/>
            {children}
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
